# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/cmake-gui

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nmoya/CGAL-4.2/demo/Incremental_Delaunay

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nmoya/CGAL-4.2/demo/Incremental_Delaunay

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/cmake-gui -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoya/CGAL-4.2/demo/Incremental_Delaunay/CMakeFiles /home/nmoya/CGAL-4.2/demo/Incremental_Delaunay/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nmoya/CGAL-4.2/demo/Incremental_Delaunay/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Delaunay_triangulation_2

# Build rule for target.
Delaunay_triangulation_2: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Delaunay_triangulation_2
.PHONY : Delaunay_triangulation_2

# fast build rule for target.
Delaunay_triangulation_2/fast:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/build
.PHONY : Delaunay_triangulation_2/fast

Delaunay_triangulation_2.o: Delaunay_triangulation_2.cpp.o
.PHONY : Delaunay_triangulation_2.o

# target to build an object file
Delaunay_triangulation_2.cpp.o:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/Delaunay_triangulation_2.cpp.o
.PHONY : Delaunay_triangulation_2.cpp.o

Delaunay_triangulation_2.i: Delaunay_triangulation_2.cpp.i
.PHONY : Delaunay_triangulation_2.i

# target to preprocess a source file
Delaunay_triangulation_2.cpp.i:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/Delaunay_triangulation_2.cpp.i
.PHONY : Delaunay_triangulation_2.cpp.i

Delaunay_triangulation_2.s: Delaunay_triangulation_2.cpp.s
.PHONY : Delaunay_triangulation_2.s

# target to generate assembly for a file
Delaunay_triangulation_2.cpp.s:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/Delaunay_triangulation_2.cpp.s
.PHONY : Delaunay_triangulation_2.cpp.s

qrc_Delaunay_triangulation_2.o: qrc_Delaunay_triangulation_2.cxx.o
.PHONY : qrc_Delaunay_triangulation_2.o

# target to build an object file
qrc_Delaunay_triangulation_2.cxx.o:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/qrc_Delaunay_triangulation_2.cxx.o
.PHONY : qrc_Delaunay_triangulation_2.cxx.o

qrc_Delaunay_triangulation_2.i: qrc_Delaunay_triangulation_2.cxx.i
.PHONY : qrc_Delaunay_triangulation_2.i

# target to preprocess a source file
qrc_Delaunay_triangulation_2.cxx.i:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/qrc_Delaunay_triangulation_2.cxx.i
.PHONY : qrc_Delaunay_triangulation_2.cxx.i

qrc_Delaunay_triangulation_2.s: qrc_Delaunay_triangulation_2.cxx.s
.PHONY : qrc_Delaunay_triangulation_2.s

# target to generate assembly for a file
qrc_Delaunay_triangulation_2.cxx.s:
	$(MAKE) -f CMakeFiles/Delaunay_triangulation_2.dir/build.make CMakeFiles/Delaunay_triangulation_2.dir/qrc_Delaunay_triangulation_2.cxx.s
.PHONY : qrc_Delaunay_triangulation_2.cxx.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Delaunay_triangulation_2"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Delaunay_triangulation_2.o"
	@echo "... Delaunay_triangulation_2.i"
	@echo "... Delaunay_triangulation_2.s"
	@echo "... qrc_Delaunay_triangulation_2.o"
	@echo "... qrc_Delaunay_triangulation_2.i"
	@echo "... qrc_Delaunay_triangulation_2.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

